### PR TITLE
fix scala 2.10 compilation

### PR DESCRIPTION
**Pull request by jtjeferreira**
# Pull Request Checklist

* [X] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X] Have you read through the [contributor guidelines](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/CONTRIBUTING.md#reactivemongo-developer--contributor-guidelines)?
* [X] Have you added tests for any changed functionality?

## Fixes

Although scala 2.10 is still a supported target, Travis was not configured to compile with scala 2.10. This PR fixes that and also an compilation issue in tests...

## Purpose

Adds scala 2.10 compilation to travis.yml

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -32,6 +32,14 @@ matrix:
     env: CI_CATEGORY=UNIT_TESTS
     jdk: oraclejdk9
     scala: 2.12.6
+  - os: linux
```
Comment (cchantep) [inline .travis.yml]: Those are not tested on purpose (2.10 support will be removed, 2.11/java9 built for integration test, ..., test matrix is already quite large)

File: driver/src/main/scala/api/commands/GroupAggregation.scala [hunk 2]
```diff
@@ -5,7 +5,7 @@ import reactivemongo.api.SerializationPack
 private[commands] trait GroupAggregation[P <: SerializationPack] {
   aggregation: AggregationFramework[P] =>
 
-  @inline private def document(name: String, arg: pack.Value): pack.Document =
+  @inline private def $document(name: String, arg: pack.Value): pack.Document =
```
Comment (cchantep) [inline driver/src/main/scala/api/commands/GroupAggregation.scala]: Do see the point

File: .travis.yml (hunk 1 above)
Comment (jtjeferreira) [reply .travis.yml]: want me to remove 2.10 support from the build?

File: driver/src/main/scala/api/commands/GroupAggregation.scala (hunk 2 above)
Comment (jtjeferreira) [reply driver/src/main/scala/api/commands/GroupAggregation.scala]: In 2.10 I have 6 compilation errors like these:

```
[info] Compiling 33 Scala sources and 1 Java source to /home/joao/git/ReactiveMongo/driver/target/scala-2.10/test-classes ...
[error] /home/joao/git/ReactiveMongo/driver/src/test/scala/AggregationSpec.scala:105:19: method document in trait GroupAggregation cannot be accessed in c.AggregationFramework
[error]             Match(document("totalPop" -> document(f"$$gte" -> 10000000L))))
```

Because there is a clash between this `reactivemongo.api.commands.GroupAggregation#document` method and the `reactivemongo.bson.`package`#document` method even though the first is private...

This is not a problem in 2.11 or 2.12...

File: .travis.yml (hunk 1 above)
Comment (cchantep) [reply .travis.yml]: not to re-add it to the CI matrix

File: driver/src/main/scala/api/commands/GroupAggregation.scala (hunk 2 above)
Comment (jtjeferreira) [reply driver/src/main/scala/api/commands/GroupAggregation.scala]: ok, will try to do that later

File: .travis.yml (hunk 1 above)
Comment (jtjeferreira) [reply .travis.yml]: you want me to revert all the changes on this file, and you will remove the support for 2.10 in another PR?

**Comment by cchantep** [comment]
Fixed at https://github.com/ReactiveMongo/ReactiveMongo/pull/773/files#diff-7ead187e5d5b55428cf9ff3b4a899884R99

**Comment by jtjeferreira** [comment]
> Fixed at ReactiveMongo/ReactiveMongo/pull/773/files#diff-7ead187e5d5b55428cf9ff3b4a899884R99

Thx
